/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 ./public/models/boeing_777_free_interior/scene.gltf --types -T
Author: Henry Chi (https://sketchfab.com/henrychi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/boeing-777-free-interior-861878c67a6a4a3faa46107065eddbfc
Title: boeing 777 FREE INTERIOR
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_19: THREE.Mesh
    Object_20: THREE.Mesh
    Object_21: THREE.Mesh
    Object_22: THREE.Mesh
    Object_23: THREE.Mesh
    Object_24: THREE.Mesh
    Object_25: THREE.Mesh
    Object_26: THREE.Mesh
    Object_27: THREE.Mesh
    Object_28: THREE.Mesh
    Object_29: THREE.Mesh
    Object_30: THREE.Mesh
    Object_31: THREE.Mesh
    Object_32: THREE.Mesh
    Object_33: THREE.Mesh
    Object_34: THREE.Mesh
    Object_35: THREE.Mesh
    Object_36: THREE.Mesh
    Object_37: THREE.Mesh
    Object_38: THREE.Mesh
    Object_39: THREE.Mesh
    Object_40: THREE.Mesh
    Object_41: THREE.Mesh
    Object_42: THREE.Mesh
    Object_43: THREE.Mesh
    Object_44: THREE.Mesh
    Object_45: THREE.Mesh
    Object_46: THREE.Mesh
    Object_47: THREE.Mesh
    Object_48: THREE.Mesh
    Object_49: THREE.Mesh
    Object_50: THREE.Mesh
    Object_51: THREE.Mesh
    Object_52: THREE.Mesh
    Object_53: THREE.Mesh
    Object_54: THREE.Mesh
    Object_55: THREE.Mesh
    Object_56: THREE.Mesh
    Object_57: THREE.Mesh
    Object_58: THREE.Mesh
    Object_59: THREE.Mesh
    Object_60: THREE.Mesh
    Object_61: THREE.Mesh
    Object_62: THREE.Mesh
    Object_63: THREE.Mesh
    Object_64: THREE.Mesh
    Object_65: THREE.Mesh
    Object_66: THREE.Mesh
    Object_67: THREE.Mesh
    Object_68: THREE.Mesh
    Object_69: THREE.Mesh
    Object_70: THREE.Mesh
    Object_71: THREE.Mesh
    Object_72: THREE.Mesh
    Object_73: THREE.Mesh
    Object_74: THREE.Mesh
    Object_75: THREE.Mesh
    Object_76: THREE.Mesh
    Object_77: THREE.Mesh
    Object_78: THREE.Mesh
    Object_79: THREE.Mesh
    Object_80: THREE.Mesh
    Object_81: THREE.Mesh
    Object_82: THREE.Mesh
    Object_83: THREE.Mesh
    Object_84: THREE.Mesh
    Object_85: THREE.Mesh
    Object_86: THREE.Mesh
    Object_87: THREE.Mesh
    Object_88: THREE.Mesh
    Object_89: THREE.Mesh
    Object_90: THREE.Mesh
    Object_91: THREE.Mesh
    Object_92: THREE.Mesh
    Object_93: THREE.Mesh
    Object_94: THREE.Mesh
    Object_95: THREE.Mesh
    Object_96: THREE.Mesh
    Object_97: THREE.Mesh
    Object_98: THREE.Mesh
    Object_99: THREE.Mesh
    Object_100: THREE.Mesh
    Object_101: THREE.Mesh
    Object_102: THREE.Mesh
    Object_103: THREE.Mesh
    Object_104: THREE.Mesh
    Object_105: THREE.Mesh
    Object_106: THREE.Mesh
    Object_107: THREE.Mesh
    Object_108: THREE.Mesh
    Object_109: THREE.Mesh
    Object_110: THREE.Mesh
    Object_111: THREE.Mesh
    Object_112: THREE.Mesh
    Object_113: THREE.Mesh
    Object_114: THREE.Mesh
    Object_115: THREE.Mesh
    Object_116: THREE.Mesh
    Object_117: THREE.Mesh
    Object_118: THREE.Mesh
    Object_119: THREE.Mesh
    Object_120: THREE.Mesh
    Object_121: THREE.Mesh
    Object_122: THREE.Mesh
    Object_123: THREE.Mesh
    Object_124: THREE.Mesh
    Object_125: THREE.Mesh
    Object_126: THREE.Mesh
    Object_127: THREE.Mesh
    Object_128: THREE.Mesh
    Object_129: THREE.Mesh
    Object_130: THREE.Mesh
    Object_131: THREE.Mesh
    Object_132: THREE.Mesh
    Object_133: THREE.Mesh
    Object_134: THREE.Mesh
    Object_135: THREE.Mesh
    Object_136: THREE.Mesh
    Object_137: THREE.Mesh
    Object_138: THREE.Mesh
    Object_139: THREE.Mesh
    Object_140: THREE.Mesh
    Object_141: THREE.Mesh
    Object_142: THREE.Mesh
    Object_143: THREE.Mesh
    Object_144: THREE.Mesh
    Object_145: THREE.Mesh
    Object_146: THREE.Mesh
    Object_147: THREE.Mesh
    Object_148: THREE.Mesh
    Object_149: THREE.Mesh
    Object_150: THREE.Mesh
    Object_151: THREE.Mesh
    Object_152: THREE.Mesh
    Object_153: THREE.Mesh
    Object_154: THREE.Mesh
    Object_155: THREE.Mesh
    Object_156: THREE.Mesh
    Object_157: THREE.Mesh
    Object_158: THREE.Mesh
    Object_159: THREE.Mesh
    Object_160: THREE.Mesh
    Object_161: THREE.Mesh
    Object_162: THREE.Mesh
    Object_163: THREE.Mesh
    Object_164: THREE.Mesh
    Object_165: THREE.Mesh
    Object_166: THREE.Mesh
    Object_167: THREE.Mesh
    Object_168: THREE.Mesh
    Object_169: THREE.Mesh
    Object_170: THREE.Mesh
    Object_171: THREE.Mesh
    Object_172: THREE.Mesh
    Object_173: THREE.Mesh
    Object_174: THREE.Mesh
    Object_175: THREE.Mesh
    Object_176: THREE.Mesh
    Object_177: THREE.Mesh
    Object_178: THREE.Mesh
    Object_179: THREE.Mesh
    Object_180: THREE.Mesh
    Object_181: THREE.Mesh
    Object_182: THREE.Mesh
    Object_183: THREE.Mesh
    Object_184: THREE.Mesh
    Object_185: THREE.Mesh
    Object_186: THREE.Mesh
    Object_187: THREE.Mesh
    Object_188: THREE.Mesh
    Object_189: THREE.Mesh
    Object_190: THREE.Mesh
    Object_191: THREE.Mesh
    Object_192: THREE.Mesh
    Object_193: THREE.Mesh
    Object_194: THREE.Mesh
    Object_195: THREE.Mesh
    Object_196: THREE.Mesh
    Object_197: THREE.Mesh
  }
  materials: {
    DarkBlue_2: THREE.MeshStandardMaterial
    Color_000: THREE.MeshStandardMaterial
    ['0129_WhiteSmoke']: THREE.MeshStandardMaterial
    Red_1: THREE.MeshStandardMaterial
    Another_Fine_Mesh: THREE.MeshStandardMaterial
    Brown: THREE.MeshStandardMaterial
    CWTF_Twin_APSc: THREE.MeshStandardMaterial
    Carpet_Aqua: THREE.MeshStandardMaterial
    Carpet_Aqua5: THREE.MeshStandardMaterial
    Carpet_Ltblue4: THREE.MeshStandardMaterial
    Color_A02: THREE.MeshStandardMaterial
    Color_A03: THREE.MeshStandardMaterial
    Color_A04: THREE.MeshStandardMaterial
    Color_B02: THREE.MeshStandardMaterial
    Color_B18: THREE.MeshStandardMaterial
    Color_E10: THREE.MeshStandardMaterial
    Concrete_Form_4x8: THREE.MeshStandardMaterial
    CoolGray4: THREE.MeshStandardMaterial
    Carpet_Low_Gray: THREE.MeshStandardMaterial
    Carpet_Ltblue2: THREE.MeshStandardMaterial
    Color_001: THREE.MeshStandardMaterial
    Color_003: THREE.MeshStandardMaterial
    Color_004: THREE.MeshStandardMaterial
    Color_005: THREE.MeshStandardMaterial
    Color_008: THREE.MeshStandardMaterial
    Color_009: THREE.MeshStandardMaterial
    Color_A01: THREE.MeshStandardMaterial
    CoolGray5: THREE.MeshStandardMaterial
    CoolGray6: THREE.MeshStandardMaterial
    CoolGray8: THREE.MeshStandardMaterial
    M_0019_Crimson: THREE.MeshStandardMaterial
    M_0020_Red: THREE.MeshStandardMaterial
    M_0044_DarkGoldenrod: THREE.MeshStandardMaterial
    M_0077_DarkGreen: THREE.MeshStandardMaterial
    M_0131_Silver: THREE.MeshStandardMaterial
    M_0134_DimGray: THREE.MeshStandardMaterial
    M_0136_Charcoal: THREE.MeshStandardMaterial
    Metal_Aluminum_Anodized: THREE.MeshStandardMaterial
    Rack___Front: THREE.MeshStandardMaterial
    Rack___Side: THREE.MeshStandardMaterial
    Translucent_Glass_Gray: THREE.MeshStandardMaterial
    Translucent_Wave: THREE.MeshStandardMaterial
    Stone_Brushed_Khaki: THREE.MeshStandardMaterial
    Metal_Brushed: THREE.MeshStandardMaterial
    Metal_Corrogated_Shiny: THREE.MeshStandardMaterial
    Metal_Rough1: THREE.MeshStandardMaterial
    Color_001_1: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    CorrogateShiny: THREE.MeshStandardMaterial
    CorrogateShiny_2: THREE.MeshStandardMaterial
    DarkGray: THREE.MeshStandardMaterial
    Rack___Top: THREE.MeshStandardMaterial
    Wood_OSB: THREE.MeshStandardMaterial
    ['0102_RoyalBlue']: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    Black_1: THREE.MeshStandardMaterial
    Charcoal: THREE.MeshStandardMaterial
    Charcoal_1: THREE.MeshStandardMaterial
    Gainsboro: THREE.MeshStandardMaterial
    Gainsboro_1: THREE.MeshStandardMaterial
    Gray3: THREE.MeshStandardMaterial
    Gray_Glass_1: THREE.MeshStandardMaterial
    Ivory: THREE.MeshStandardMaterial
    Maroon: THREE.MeshStandardMaterial
    Redwood: THREE.MeshStandardMaterial
    Silver: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.DarkBlue_2} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['0129_WhiteSmoke']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Red_1} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Another_Fine_Mesh} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Brown} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.CWTF_Twin_APSc} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Carpet_Aqua} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Carpet_Aqua} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Carpet_Aqua} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Carpet_Aqua} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Carpet_Aqua} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Carpet_Aqua} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Carpet_Aqua} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Carpet_Aqua} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Carpet_Aqua} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Carpet_Aqua} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.Carpet_Aqua} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Carpet_Aqua} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.Carpet_Aqua} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.Carpet_Aqua} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.Carpet_Aqua5} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.Carpet_Ltblue4} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.Color_A02} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.Color_A03} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.Color_A04} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.Color_A04} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.Color_B02} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.Color_B18} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.Color_E10} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.Concrete_Form_4x8} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.CoolGray4} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.CoolGray4} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.CoolGray4} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.CoolGray4} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.CoolGray4} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.CoolGray4} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.Carpet_Low_Gray} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.Carpet_Low_Gray} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.Carpet_Low_Gray} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.Carpet_Low_Gray} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.Carpet_Low_Gray} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.Carpet_Low_Gray} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.Carpet_Low_Gray} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.Carpet_Low_Gray} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.Carpet_Low_Gray} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.Carpet_Low_Gray} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.Carpet_Low_Gray} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.Carpet_Low_Gray} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.Carpet_Low_Gray} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.Carpet_Low_Gray} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.Carpet_Low_Gray} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.Carpet_Ltblue2} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.Color_001} />
        <mesh geometry={nodes.Object_57.geometry} material={materials.Color_003} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.Color_003} />
        <mesh geometry={nodes.Object_59.geometry} material={materials.Color_003} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.Color_004} />
        <mesh geometry={nodes.Object_61.geometry} material={materials.Color_005} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.Color_005} />
        <mesh geometry={nodes.Object_63.geometry} material={materials.Color_005} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.Color_005} />
        <mesh geometry={nodes.Object_65.geometry} material={materials.Color_005} />
        <mesh geometry={nodes.Object_66.geometry} material={materials.Color_005} />
        <mesh geometry={nodes.Object_67.geometry} material={materials.Color_005} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.Color_005} />
        <mesh geometry={nodes.Object_69.geometry} material={materials.Color_005} />
        <mesh geometry={nodes.Object_70.geometry} material={materials.Color_008} />
        <mesh geometry={nodes.Object_71.geometry} material={materials.Color_008} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.Color_008} />
        <mesh geometry={nodes.Object_73.geometry} material={materials.Color_008} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.Color_009} />
        <mesh geometry={nodes.Object_75.geometry} material={materials.Color_A01} />
        <mesh geometry={nodes.Object_76.geometry} material={materials.CoolGray5} />
        <mesh geometry={nodes.Object_77.geometry} material={materials.CoolGray6} />
        <mesh geometry={nodes.Object_78.geometry} material={materials.CoolGray8} />
        <mesh geometry={nodes.Object_79.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.Object_80.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.Object_81.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.Object_82.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.Object_83.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.Object_84.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.Object_85.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.Object_86.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.Object_87.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.Object_88.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.Object_89.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.Object_90.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.Object_91.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.Object_92.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.Object_93.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.Object_94.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.Object_95.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.Object_96.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.Object_97.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.Object_98.geometry} material={materials.M_0019_Crimson} />
        <mesh geometry={nodes.Object_99.geometry} material={materials.M_0020_Red} />
        <mesh geometry={nodes.Object_100.geometry} material={materials.M_0044_DarkGoldenrod} />
        <mesh geometry={nodes.Object_101.geometry} material={materials.M_0077_DarkGreen} />
        <mesh geometry={nodes.Object_102.geometry} material={materials.M_0131_Silver} />
        <mesh geometry={nodes.Object_103.geometry} material={materials.M_0131_Silver} />
        <mesh geometry={nodes.Object_104.geometry} material={materials.M_0131_Silver} />
        <mesh geometry={nodes.Object_105.geometry} material={materials.M_0131_Silver} />
        <mesh geometry={nodes.Object_106.geometry} material={materials.M_0131_Silver} />
        <mesh geometry={nodes.Object_107.geometry} material={materials.M_0131_Silver} />
        <mesh geometry={nodes.Object_108.geometry} material={materials.M_0131_Silver} />
        <mesh geometry={nodes.Object_109.geometry} material={materials.M_0131_Silver} />
        <mesh geometry={nodes.Object_110.geometry} material={materials.M_0131_Silver} />
        <mesh geometry={nodes.Object_111.geometry} material={materials.M_0131_Silver} />
        <mesh geometry={nodes.Object_112.geometry} material={materials.M_0131_Silver} />
        <mesh geometry={nodes.Object_113.geometry} material={materials.M_0131_Silver} />
        <mesh geometry={nodes.Object_114.geometry} material={materials.M_0131_Silver} />
        <mesh geometry={nodes.Object_115.geometry} material={materials.M_0134_DimGray} />
        <mesh geometry={nodes.Object_116.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_117.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_118.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_119.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_120.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_121.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_122.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_123.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_124.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_125.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_126.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_127.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_128.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_129.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_130.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_131.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_132.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_133.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_134.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_135.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_136.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_137.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_138.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_139.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_140.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_141.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_142.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_143.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_144.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_145.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_146.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_147.geometry} material={materials.Metal_Aluminum_Anodized} />
        <mesh geometry={nodes.Object_148.geometry} material={materials.Metal_Aluminum_Anodized} />
        <mesh geometry={nodes.Object_149.geometry} material={materials.Rack___Front} />
        <mesh geometry={nodes.Object_150.geometry} material={materials.Rack___Side} />
        <mesh geometry={nodes.Object_151.geometry} material={materials.Translucent_Glass_Gray} />
        <mesh geometry={nodes.Object_152.geometry} material={materials.Translucent_Wave} />
        <mesh geometry={nodes.Object_153.geometry} material={materials.Stone_Brushed_Khaki} />
        <mesh geometry={nodes.Object_154.geometry} material={materials.Metal_Brushed} />
        <mesh geometry={nodes.Object_155.geometry} material={materials.Metal_Brushed} />
        <mesh geometry={nodes.Object_156.geometry} material={materials.Metal_Brushed} />
        <mesh geometry={nodes.Object_157.geometry} material={materials.Metal_Brushed} />
        <mesh geometry={nodes.Object_158.geometry} material={materials.Metal_Brushed} />
        <mesh geometry={nodes.Object_159.geometry} material={materials.Metal_Brushed} />
        <mesh geometry={nodes.Object_160.geometry} material={materials.Metal_Brushed} />
        <mesh geometry={nodes.Object_161.geometry} material={materials.Metal_Corrogated_Shiny} />
        <mesh geometry={nodes.Object_162.geometry} material={materials.Metal_Rough1} />
        <mesh geometry={nodes.Object_163.geometry} material={materials.Color_001_1} />
        <mesh geometry={nodes.Object_164.geometry} material={materials.Black} />
        <mesh geometry={nodes.Object_165.geometry} material={materials.CoolGray8} />
        <mesh geometry={nodes.Object_166.geometry} material={materials.CoolGray8} />
        <mesh geometry={nodes.Object_167.geometry} material={materials.CoolGray8} />
        <mesh geometry={nodes.Object_168.geometry} material={materials.CoolGray8} />
        <mesh geometry={nodes.Object_169.geometry} material={materials.CorrogateShiny} />
        <mesh geometry={nodes.Object_170.geometry} material={materials.CorrogateShiny_2} />
        <mesh geometry={nodes.Object_171.geometry} material={materials.DarkGray} />
        <mesh geometry={nodes.Object_172.geometry} material={materials.Rack___Top} />
        <mesh geometry={nodes.Object_173.geometry} material={materials.Wood_OSB} />
        <mesh geometry={nodes.Object_174.geometry} material={materials['0102_RoyalBlue']} />
        <mesh geometry={nodes.Object_175.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_176.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_177.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_178.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_179.geometry} material={materials.Black} />
        <mesh geometry={nodes.Object_180.geometry} material={materials.Black} />
        <mesh geometry={nodes.Object_181.geometry} material={materials.Black_1} />
        <mesh geometry={nodes.Object_182.geometry} material={materials.Black_1} />
        <mesh geometry={nodes.Object_183.geometry} material={materials.Charcoal} />
        <mesh geometry={nodes.Object_184.geometry} material={materials.Charcoal} />
        <mesh geometry={nodes.Object_185.geometry} material={materials.Charcoal_1} />
        <mesh geometry={nodes.Object_186.geometry} material={materials.Color_A01} />
        <mesh geometry={nodes.Object_187.geometry} material={materials.Gainsboro} />
        <mesh geometry={nodes.Object_188.geometry} material={materials.Gainsboro_1} />
        <mesh geometry={nodes.Object_189.geometry} material={materials.Gray3} />
        <mesh geometry={nodes.Object_190.geometry} material={materials.Translucent_Glass_Gray} />
        <mesh geometry={nodes.Object_191.geometry} material={materials.Gray_Glass_1} />
        <mesh geometry={nodes.Object_192.geometry} material={materials.Ivory} />
        <mesh geometry={nodes.Object_193.geometry} material={materials.Maroon} />
        <mesh geometry={nodes.Object_194.geometry} material={materials.Color_A01} />
        <mesh geometry={nodes.Object_195.geometry} material={materials.Redwood} />
        <mesh geometry={nodes.Object_196.geometry} material={materials.Silver} />
        <mesh geometry={nodes.Object_197.geometry} material={materials.Color_000} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
