/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 ./public/models/PlaneCockpit.glb --types -T -R -S --root ./public/models
Author: Henry Chi (https://sketchfab.com/henrychi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-plane-cockpit-09ba86525638447d90f6daa2eb43475e
Title: FREE plane cockpit
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_17: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_21: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_23: THREE.Mesh;
    Object_24: THREE.Mesh;
    Object_25: THREE.Mesh;
    Object_26: THREE.Mesh;
    Object_27: THREE.Mesh;
    Object_28: THREE.Mesh;
    Object_29: THREE.Mesh;
    Object_30: THREE.Mesh;
    Object_31: THREE.Mesh;
    Object_32: THREE.Mesh;
    Object_33: THREE.Mesh;
    Object_34: THREE.Mesh;
    Object_35: THREE.Mesh;
    Object_36: THREE.Mesh;
    Object_37: THREE.Mesh;
    Object_38: THREE.Mesh;
    Object_39: THREE.Mesh;
    Object_40: THREE.Mesh;
    Object_41: THREE.Mesh;
    Object_42: THREE.Mesh;
    Object_43: THREE.Mesh;
    Object_44: THREE.Mesh;
    Object_45: THREE.Mesh;
    Object_46: THREE.Mesh;
  };
  materials: {
    Carpet_Loop_Pattern: THREE.MeshStandardMaterial;
    Color_005: THREE.MeshStandardMaterial;
    Color_009: THREE.MeshStandardMaterial;
    Color_D24: THREE.MeshStandardMaterial;
    Fencing_Construction: THREE.MeshStandardMaterial;
    Instrument_ND: THREE.MeshStandardMaterial;
    M_2D: THREE.MeshStandardMaterial;
    WILCO_777_2D: THREE.MeshStandardMaterial;
    Groundcover_Brick_Crushed_1: THREE.MeshStandardMaterial;
    anemo: THREE.MeshStandardMaterial;
    Brick_Basket_Two: THREE.MeshStandardMaterial;
    Color_000: THREE.MeshStandardMaterial;
    Color_001: THREE.MeshStandardMaterial;
    Color_002: THREE.MeshStandardMaterial;
    Color_008: THREE.MeshStandardMaterial;
    Color_A01: THREE.MeshStandardMaterial;
    Color_C01: THREE.MeshStandardMaterial;
    Color_C19: THREE.MeshStandardMaterial;
    Groundcover_Brick_Crushed: THREE.MeshStandardMaterial;
    Instrument: THREE.MeshStandardMaterial;
    M_0129_WhiteSmoke: THREE.MeshStandardMaterial;
    M_0136_Charcoal: THREE.MeshStandardMaterial;
    material: THREE.MeshStandardMaterial;
    Metal_Aluminum_Anodized: THREE.MeshStandardMaterial;
    Metal_Seamed: THREE.MeshStandardMaterial;
    material_25: THREE.MeshStandardMaterial;
    material_26: THREE.MeshStandardMaterial;
    material_27: THREE.MeshStandardMaterial;
    material_28: THREE.MeshStandardMaterial;
    Beige_1: THREE.MeshStandardMaterial;
    DimGray: THREE.MeshStandardMaterial;
    Gray6: THREE.MeshStandardMaterial;
    LightGray: THREE.MeshStandardMaterial;
    LightGray_1: THREE.MeshStandardMaterial;
    nivess: THREE.MeshStandardMaterial;
    pic_02_1: THREE.MeshStandardMaterial;
  };
};

type PlaneCockpitProps = JSX.IntrinsicElements["group"] & {
  controlsPitch: number;
  groupRef?: React.MutableRefObject<THREE.Group>;
};

export default function Model({ controlsPitch, groupRef, ...props }: PlaneCockpitProps) {
  const { nodes, materials } = useGLTF(
    "/models/PlaneCockpit-transformed.glb"
  ) as unknown as GLTFResult;

  return (
    <group {...props} ref={groupRef} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Carpet_Loop_Pattern} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Color_005} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Color_009} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Color_D24} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Fencing_Construction} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Instrument_ND} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.M_2D} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.WILCO_777_2D} />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.Groundcover_Brick_Crushed_1}
        />
        <mesh geometry={nodes.Object_11.geometry} material={materials.anemo} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Color_009} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Brick_Basket_Two} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Color_001} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Color_002} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Color_008} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Color_A01} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.Color_C01} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.Groundcover_Brick_Crushed} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.Instrument} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.Color_A01} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.M_0129_WhiteSmoke} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Color_C19} />
        <group rotation={[controlsPitch, 0, 0]}>
          <mesh geometry={nodes.Object_28.geometry} material={materials.Metal_Aluminum_Anodized} />
          <mesh geometry={nodes.Object_29.geometry} material={materials.Metal_Seamed} />
          <mesh geometry={nodes.Object_34.geometry} material={materials.Beige_1} />
        </group>
        <mesh geometry={nodes.Object_31.geometry} material={materials.material_26} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.material_25} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.material_27} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.material_28} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.Color_009} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.Color_009} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.Color_009} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.DimGray} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.Gray6} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.LightGray} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.LightGray_1} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.anemo} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.nivess} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.pic_02_1} />
      </group>
    </group>
  );
}

useGLTF.preload("/models/PlaneCockpit-transformed.glb");
